### ISSUE TITLE
Custody tracking does not check output files for UnpackArchiveStep

### ISSUE THREAD

**Issue by pydsigner** [pydsigner/anchovy#70]
Related to #60, #66, and #67. After these three custody fixes, only the target directory for `UnpackArchiveStep` is being checked for existence, not the the files that come from the the archive. This means that when the purge flag is supplied but the `UnpackArchiveStep` is outputting into a non-transient directory like a build-cache working dir or output dir, the Step is not marked as needing to be refreshed and the entry_from_path call when skip_step is run errors out on the missing files.

```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "<snip>\anchovy\.venv\Scripts\anchovy.exe\__main__.py", line 7, in <module>
  File "<snip>\anchovy\src\anchovy\cli.py", line 225, in main
    run_from_rules(settings, rules, custodian, argv=remaining, prog=f'anchovy {label}')
  File "<snip>\anchovy\src\anchovy\cli.py", line 119, in run_from_rules
    context.run()
  File "<snip>\anchovy\src\anchovy\core.py", line 190, in run
    self.process(input_paths)
  File "<snip>\anchovy\src\anchovy\core.py", line 168, in process
    output_paths = self.custodian.skip_step(path, output_paths)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>\anchovy\src\anchovy\custody.py", line 234, in skip_step
    for o_entry in map(self.entry_from_path, prior_outputs):
  File "<snip>\anchovy\src\anchovy\custody.py", line 142, in entry_from_path
    stat = path.stat()
           ^^^^^^^^^^^
  File "<snip>\pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'working\\code_index\\basic_site.py'
```

**Comment by pydsigner** [comment]
The issue is there are several file relationship cases:
* initial `input_path`, `output_paths` == final `input_paths`, `output_paths`
  For example, returning None from `Step.__call__()`. This case is handled properly and easily.
* initial `input_path` != final `input_paths`
  For example, JinjaExtendedMarkdownStep pulling in a template, but only writing to the specified output file(s). This case is handled using Custodian.find_upstream() to check any additional files that affected the last generation of a given output.
* initial `output_paths` != final `output_paths`
  For example, our current case with UnpackArchiveStep. This is not handled.
